- set_fact: database_type=postgis

- name: set specific variables for distributions
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version}}.yml"
    - "default.yml"

- name: ensure geo packages are installed
  apt: pkg={{ item }} state=present
  with_items:
      - binutils
      - libproj-dev
      - gdal-bin
      - "{{ postgis_package_name }}"
  become: yes
